[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Ivan Rybachyk <ivan2005rubachyk@gmail.com>"]
license = "MIT"

[workspace.dependencies]
rand = { version = "0.8.5" }

[workspace]
resolver = "3"
members = [
    "hw1",
    "hw2",
    "hw3",
    "hw4"
]

